version : '3.4'

services:
  app:
    container_name: mallet-golf
    network_mode: host
    restart: always
    build : .
    ports:
      - "8080:8080"

    depends_on:
      - db

  db:
    container_name: mongod
    network_mode: host
    image : mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
